using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Magicallity.Shared
{
    public class VehicleModel
    {
        public VehicleModel(string dis, string mod, int pri) { displayName = dis; modelName = mod; price = pri; }
        public VehicleModel(string dis, string mod, int pri, string vehCat) { displayName = dis; modelName = mod; price = pri; vehicleCategory = vehCat; }
        public string displayName;
        public string modelName;
        public int price;
        public string vehicleCategory;
    }

    public static class VehicleStoreItems
    {
        public static Dictionary<string, List<VehicleModel>> StoreMenus = new Dictionary<string, List<VehicleModel>>()
        {
            ["VehicleStore"] = new List<VehicleModel>()
            {
                new VehicleModel("VW Beetle 74", "beetle74", 23500, "Compacts"),
                new VehicleModel("Honda City Turbo", "city85", 13500, "Compacts"),
                new VehicleModel("Blista Compact", "blista2", 14500, "Compacts"),
                new VehicleModel("Blista", "blista", 18000, "Compacts"),
                new VehicleModel("Brioso R/A", "brioso", 15000, "Compacts"),
                new VehicleModel("Dilettante", "dilettante", 17000, "Compacts"),
                new VehicleModel("Issi", "issi2", 16000, "Compacts"),
                new VehicleModel("Issi Retro", "issi3", 18000, "Compacts"),
                new VehicleModel("Panto", "panto", 11000, "Compacts"),
                new VehicleModel("Prairie", "prairie", 14000, "Compacts"),
                new VehicleModel("Rhapsody", "rhapsody", 12000, "Compacts"),
                new VehicleModel("Cheburek", "cheburek", 13000, "Classics"),
                new VehicleModel("Fagaloa", "fagaloa", 16000, "Classics"),
                new VehicleModel("Cognoscenti Cabrio", "cogcabrio", 45000, "Coupes"),
                new VehicleModel("Exemplar", "exemplar", 38000, "Coupes"),
                new VehicleModel("F620", "f620", 75000, "Coupes"),
                new VehicleModel("Felon GT", "felon2", 60000, "Coupes"),
                new VehicleModel("Felon", "felon", 50000, "Coupes"),
                new VehicleModel("Jackal", "jackal", 28000, "Coupes"),
                new VehicleModel("Oracle XS", "oracle2", 42000, "Coupes"),
                new VehicleModel("Oracle", "oracle", 38000, "Coupes"),
                new VehicleModel("Sentinel XS", "sentinel2", 42000, "Coupes"),
                new VehicleModel("Sentinel", "sentinel", 35000, "Coupes"),
                new VehicleModel("Windsor Drop", "windsor2", 140000, "Coupes"),
                new VehicleModel("Windsor", "windsor", 120000, "Coupes"),
                new VehicleModel("Zion Cabrio", "zion2", 40000, "Coupes"),
                new VehicleModel("Zion", "zion", 34000, "Coupes"),
                new VehicleModel("Plymouth Superbird 70", "superbird", 55500, "Muscle"),
                new VehicleModel("Blade", "blade", 6500, "Muscle"),
                new VehicleModel("Buccaneer", "buccaneer", 15000, "Muscle"),
                new VehicleModel("Chino", "chino", 18000, "Muscle"),
                new VehicleModel("Chino 2", "chino2", 26000, "Muscle"),
                new VehicleModel("Dominator", "dominator", 30000, "Muscle"),
                new VehicleModel("Dominator GTX", "dominator3", 55000, "Muscle"),
                new VehicleModel("Dukes", "dukes", 29000, "Muscle"),
                new VehicleModel("Ellie", "ellie", 32000, "Muscle"),
                new VehicleModel("Faction", "faction", 9000, "Muscle"),
                new VehicleModel("Faction Custom", "faction2", 18000, "Muscle"),
                new VehicleModel("Faction Custom 2", "faction3", 26000, "Muscle"),
                new VehicleModel("Gauntlet", "gauntlet", 32000, "Muscle"),
                new VehicleModel("Hotknife", "hotknife", 27000, "Muscle"),
                new VehicleModel("Hermes", "hermes", 32000, "Muscle"),
                new VehicleModel("Hustler", "hustler", 35000, "Muscle"),
                new VehicleModel("Lurcher", "lurcher", 29000, "Muscle"),
                new VehicleModel("Nightshade", "nightshade", 27000, "Muscle"),
                new VehicleModel("Phoenix", "phoenix", 25000, "Muscle"),
                new VehicleModel("Picador", "picador", 6000, "Muscle"),
                new VehicleModel("Rat-Loader", "ratloader", 28000, "Muscle"),
                new VehicleModel("Rat-Truck", "ratloader2", 35000, "Muscle"),
                new VehicleModel("Rapid GT Classic", "rapidgt3", 35000, "Muscle"),
                new VehicleModel("Ruiner", "ruiner", 12000, "Muscle"),
                new VehicleModel("Sabre Turbo", "sabregt", 24000, "Muscle"),
                new VehicleModel("Sabre Custom", "sabregt2", 24000, "Muscle"),
                new VehicleModel("Slamvan", "slamvan", 20000, "Muscle"),
                new VehicleModel("Slamvan Lost", "slamvan2", 24000, "Muscle"),
                new VehicleModel("Slamvan Custom", "slamvan3", 24000, "Muscle"),
                new VehicleModel("Stalion", "stalion", 30000, "Muscle"),
                new VehicleModel("Tampa", "tampa", 25000, "Muscle"),
                new VehicleModel("Tampa 2", "tampa2", 35000, "Muscle"),
                new VehicleModel("Vigero", "vigero", 32000, "Muscle"),
                new VehicleModel("Virgo", "virgo", 23000, "Muscle"),
                new VehicleModel("Voodoo", "voodoo", 16000, "Muscle"),
                new VehicleModel("Yosemite", "yosemite", 24000, "Muscle"),
                new VehicleModel("Toyota FJ40 Softtop", "fj40", 33000, "Off-Road"),
                new VehicleModel("Toyota FJ40 Hardtop", "fj40b", 34500, "Off-Road"),
                new VehicleModel("BJ Injection", "bfinjection", 12000, "Off-Road"),
                new VehicleModel("Bifta", "bifta", 8000, "Off-Road"),
                new VehicleModel("Blazer", "blazer", 3500, "Off-Road"),
                new VehicleModel("Blazer Flame", "blazer3", 5000, "Off-Road"),
                new VehicleModel("Bodhi", "bodhi2", 16000, "Off-Road"),
                new VehicleModel("Brawler", "brawler", 75000, "Off-Road"),
                new VehicleModel("Dloader", "dloader", 24000, "Off-Road"),
                new VehicleModel("Dune", "dune", 9000, "Off-Road"),
                new VehicleModel("Dubsta 6x6", "dubsta3", 210000, "Off-Road"),
                new VehicleModel("Guardian", "guardian", 45000, "Off-Road"),
                new VehicleModel("Kalahari", "kalahari", 18000, "Off-Road"),
                new VehicleModel("Kamacho", "kamacho", 60000, "Off-Road"),
                new VehicleModel("Rancher XL", "rancherxl", 14000, "Off-Road"),
                new VehicleModel("Rebel", "rebel", 12500, "Off-Road"),
                new VehicleModel("Rebel 2", "rebel2", 16000, "Off-Road"),
                new VehicleModel("Riata", "riata", 25000, "Off-Road"),
                new VehicleModel("Sandking", "sandking", 28000, "Off-Road"),
                new VehicleModel("Sandking 2", "sandking2", 24000, "Off-Road"),
                new VehicleModel("Streiter", "streiter", 40000, "Off-Road"),
                new VehicleModel("Trophy Truck", "trophytruck", 30000, "Off-Road"),
                new VehicleModel("Volvo 242", "v242", 7800, "Sedans"),
                new VehicleModel("Asea", "asea", 10000, "Sedans"),
                new VehicleModel("Cog55", "cog55", 70000, "Sedans"),
                new VehicleModel("Cognoscenti", "cognoscenti", 75000, "Sedans"),
                new VehicleModel("Cheburek", "cheburek", 13000, "Sedans"),
                new VehicleModel("Emperor", "emperor", 9000, "Sedans"),
                new VehicleModel("Emperor 2", "emperor2", 7000, "Sedans"),
                new VehicleModel("Fugitive", "fugitive", 24000, "Sedans"),
                new VehicleModel("Fagaloa", "fagaloa", 16000, "Sedans"),
                new VehicleModel("Glendale", "glendale", 14000, "Sedans"),
                new VehicleModel("Ingot", "ingot", 8500, "Sedans"),
                new VehicleModel("Intruder", "intruder", 23000, "Sedans"),
                new VehicleModel("Premier", "premier", 12000, "Sedans"),
                new VehicleModel("Primo", "primo", 8000, "Sedans"),
                new VehicleModel("Primo Custom", "primo2", 13000, "Sedans"),
                new VehicleModel("Regina", "regina", 12000, "Sedans"),
                new VehicleModel("Romero", "romero", 28000, "Sedans"),
                new VehicleModel("Stanier", "stanier", 11000, "Sedans"),
                new VehicleModel("Stratum", "stratum", 12000, "Sedans"),
                new VehicleModel("Stretch", "stretch", 48000, "Sedans"),
                new VehicleModel("Surge", "surge", 24000, "Sedans"),
                new VehicleModel("Tailgater", "tailgater", 28000, "Sedans"),
                new VehicleModel("Warrener", "warrener", 75000, "Sedans"),
                new VehicleModel("Washington", "washington", 12000, "Sedans"),
                new VehicleModel("9F Cabrio", "ninef2", 95000, "Sports"),
                new VehicleModel("9F", "ninef", 90000, "Sports"),
                new VehicleModel("Alpha", "alpha", 90000, "Sports"),
                new VehicleModel("Banshee", "banshee", 85000, "Sports"),
                new VehicleModel("Bestia GTS", "bestiagts", 250000, "Sports"),
                new VehicleModel("Buffalo", "buffalo", 32000, "Sports"),
                new VehicleModel("Buffalo S", "buffalo2", 48000, "Sports"),
                new VehicleModel("Carbonizzare", "carbonizzare", 175000, "Sports"),
                new VehicleModel("Comet", "comet2", 80000, "Sports"),
                new VehicleModel("Comet SR", "comet5", 95000, "Sports"),
                new VehicleModel("Coquette", "coquette", 65000, "Sports"),
                new VehicleModel("Elegy", "ELEGY2", 60000, "Sports"),
                new VehicleModel("Feltzer", "feltzer2", 85000, "Sports"),
                new VehicleModel("Furore GT", "furoregt", 75000, "Sports"),
                new VehicleModel("Fusilade", "fusilade", 20000, "Sports"),
                new VehicleModel("Flash GT", "flashgt", 60000, "Sports"),
                new VehicleModel("Futo", "futo", 23000, "Sports"),
                new VehicleModel("GB200", "gb200", 32000, "Sports"),
                new VehicleModel("Jester", "jester", 90000, "Sports"),
                new VehicleModel("Jester Retro", "jester3", 105000, "Sports"),
                new VehicleModel("Hotring", "hotring", 54000, "Sports"),
                new VehicleModel("Khamelion", "KHAMELION", 110000, "Sports"),
                new VehicleModel("Kuruma", "kuruma", 40000, "Sports"),
                new VehicleModel("Lynx", "lynx", 60000, "Sports"),
                new VehicleModel("Massacro (Racecar)", "massacro2", 175000, "Sports"),
                new VehicleModel("Massacro", "massacro", 150000, "Sports"),
                new VehicleModel("Neon", "neon", 180000, "Sports"),
                new VehicleModel("Omnis", "omnis", 125000, "Sports"),
                new VehicleModel("Penumbra", "penumbra", 23000, "Sports"),
                new VehicleModel("Rapid GT", "rapidgt", 85000, "Sports"),
                new VehicleModel("Raiden", "raiden", 90000, "Sports"),
                new VehicleModel("Raptor", "RAPTOR", 58000, "Sports"),
                new VehicleModel("Ruston", "RUSTON", 62000, "Sports"),
                new VehicleModel("Pariah", "pariah", 70000, "Sports"),
                new VehicleModel("Schwarzer", "Schwarzer", 40000, "Sports"),
                new VehicleModel("Seven-70", "SEVEN70", 425000, "Sports"),
                new VehicleModel("Sultan", "sultan", 15000, "Sports"),
                new VehicleModel("Surano", "surano", 55000, "Sports"),
                new VehicleModel("Sentinel Classic", "sentinel3", 35000, "Sports"),
                new VehicleModel("Tropos", "tropos", 125000, "Sports"),
                new VehicleModel("Verkierer", "verlierer2", 79000, "Sports"),
                new VehicleModel("190z", "z190", 125000, "Sports Classics"),
                new VehicleModel("Ardent", "ardent", 125000, "Sports Classics"),
                new VehicleModel("Casco", "casco", 150000, "Sports Classics"),
                new VehicleModel("Cheetah Classic", "cheetah2", 125000, "Sports Classics"),
                new VehicleModel("Coquette Classic", "coquette2", 80000, "Sports Classics"),
                new VehicleModel("Mamba", "mamba", 95000, "Sports Classics"),
                new VehicleModel("Manana", "manana", 18000, "Sports Classics"),
                new VehicleModel("Monroe", "monroe", 175000, "Sports Classics"),
                new VehicleModel("Michelli GT", "michelli", 80000, "Sports Classics"),
                new VehicleModel("Peyote", "peyote", 30000, "Sports Classics"),
                new VehicleModel("Infernus Classic", "infernus2", 120000, "Sports Classics"),
                new VehicleModel("Pigalle", "pigalle", 35000, "Sports Classics"),
                new VehicleModel("Stinger", "stinger", 425000, "Sports Classics"),
                new VehicleModel("Retinue", "retinue", 80000, "Sports Classics"),
                new VehicleModel("GT500", "gt500", 55000, "Sports Classics"),
                new VehicleModel("Toreno", "torero", 250000, "Sports Classics"),
                new VehicleModel("Tornado 2", "tornado2", 50000, "Sports Classics"),
                new VehicleModel("Tornado 3", "tornado3", 20000, "Sports Classics"),
                new VehicleModel("Tornado 4", "tornado4", 22000, "Sports Classics"),
                new VehicleModel("Tornado 5", "tornado5", 55000, "Sports Classics"),
                new VehicleModel("Turismo Classic", "turismo2", 55000, "Sports Classics"),
                new VehicleModel("Swinger", "winger", 120000, "Sports Classics"),
                new VehicleModel("Dodge Viper 99", "99viper", 130000, "Super"),
                new VehicleModel("Dodge Viper 16", "viper", 210000, "Super"),
                new VehicleModel("Audi R8 2013", "r8ppi", 175000, "Super"),
                new VehicleModel("Autarch", "autarch", 950000, "Super"),
                new VehicleModel("Adder", "adder", 750000, "Super"),
                new VehicleModel("Banshee 900r", "banshee2", 125000, "Super"),
                new VehicleModel("Bullet", "bullet", 100000, "Super"),
                new VehicleModel("Cheetah", "cheetah", 750000, "Super"),
                new VehicleModel("ETR1", "sheava", 250000, "Super"),
                new VehicleModel("Entity XF", "entity", 160000, "Super"),
                new VehicleModel("Entity XXR", "entity2", 250000, "Super"),
                new VehicleModel("Infernus", "infernus", 225000, "Super"),
                new VehicleModel("Italigtb", "italigtb", 120000, "Super"),
                new VehicleModel("Italigtb2", "italigtb2", 160000, "Super"),
                new VehicleModel("Nero", "nero", 750000, "Super"),
                new VehicleModel("Nero Custom", "nero", 780000, "Super"),
                new VehicleModel("Osiris", "osiris", 525000, "Super"),
                new VehicleModel("Penetrator", "penetrator", 250000, "Super"),
                new VehicleModel("Pfister811", "pfister811", 350000, "Super"),
                new VehicleModel("RE-7B", "le7b", 750000, "Super"),
                new VehicleModel("Reaper", "reaper", 160000, "Super"),
                new VehicleModel("Sultan RS", "sultanrs", 60000, "Super"),
                new VehicleModel("Specter", "specter", 125000, "Super"),
                new VehicleModel("Specter Custom", "specter", 135000, "Super"),
                new VehicleModel("SC1", "sc1", 150000, "Super"),
                new VehicleModel("T20", "t20", 125000, "Super"),
                new VehicleModel("Taipan", "taipan", 650000, "Super"),
                new VehicleModel("Tempesta", "tempesta", 180000, "Super"),
                new VehicleModel("Turismo R", "turismor", 1250000, "Super"),
                new VehicleModel("Tyrus", "tyrus", 1600000, "Super"),
                new VehicleModel("Tyrant", "tyrant", 1600000, "Super"),
                new VehicleModel("Vacca", "vacca", 135000, "Super"),
                new VehicleModel("Vagner", "vagner", 1000000, "Super"),
                new VehicleModel("Voltic", "voltic", 125000, "Super"),
                new VehicleModel("Visione", "visione", 800000, "Super"),
                new VehicleModel("X80 Proto", "prototipo", 1500000, "Super"),
                new VehicleModel("Tezeract", "tezeract", 1600000, "Super"),
                new VehicleModel("XA21", "xa21", 750000, "Super"),
                new VehicleModel("Zentorno", "zentorno", 350000, "Super"),
                new VehicleModel("Baller", "baller", 30000, "SUVs"),
                new VehicleModel("BJXL", "bjxl", 32000, "SUVs"),
                new VehicleModel("Cavalcade", "cavalcade", 35000, "SUVs"),
                new VehicleModel("Contender", "contender", 60000, "SUVs"),
                new VehicleModel("Dubsta", "dubsta", 75000, "SUVs"),
                new VehicleModel("FQ2", "fq2", 35000, "SUVs"),
                new VehicleModel("Granger", "granger", 32000, "SUVs"),
                new VehicleModel("Gresley", "gresley", 22000, "SUVs"),
                new VehicleModel("Habanero", "habanero", 35000, "SUVs"),
                new VehicleModel("Huntley", "huntley", 30000, "SUVs"),
                new VehicleModel("Landstalker", "landstalker", 32000, "SUVs"),
                new VehicleModel("Mesa 2", "mesa3", 30000, "SUVs"),
                new VehicleModel("Mesa", "mesa", 24000, "SUVs"),
                new VehicleModel("Patriot", "patriot", 25000, "SUVs"),
                new VehicleModel("Radius", "radi", 16000, "SUVs"),
                new VehicleModel("Rocoto", "rocoto", 34000, "SUVs"),
                new VehicleModel("Seminole", "seminole", 32000, "SUVs"),
                new VehicleModel("Serrano", "serrano", 22000, "SUVs"),
                new VehicleModel("XLS", "xls", 35000, "SUVs"),
                new VehicleModel("Bison", "bison", 22000, "Vans"),
                new VehicleModel("Bobcat XL", "bobcatxl", 12000, "Vans"),
                new VehicleModel("Boxville", "boxville", 26000, "Vans"),
                new VehicleModel("Burrito", "burrito", 14000, "Vans"),
                new VehicleModel("Minivan", "minivan", 18000, "Vans"),
                new VehicleModel("Moonbeam", "moonbeam", 10000, "Vans"),
                new VehicleModel("Paradise", "paradise", 12000, "Vans"),
                new VehicleModel("Pony", "pony", 14000, "Vans"),
                new VehicleModel("Rumpo", "rumpo", 8000, "Vans"),
                new VehicleModel("Speedo", "speedo", 10000, "Vans"),
                new VehicleModel("Surfer", "surfer", 14000, "Vans"),
                new VehicleModel("Youga", "youga", 9000, "Vans"),
                new VehicleModel("Fixter", "fixter", 500, "Bicycles"),
                new VehicleModel("Scorcher", "scorcher", 450, "Bicycles"),
                new VehicleModel("Cruiser", "cruiser", 200, "Bicycles"),
                new VehicleModel("BMX", "bmx", 400, "Bicycles"),
                new VehicleModel("Triathlon bike 1", "tribike", 1000, "Bicycles"),
                new VehicleModel("Triathlon bike 2", "tribike2", 1000, "Bicycles"),
                new VehicleModel("Triathlon bike 3", "tribike3", 1000, "Bicycles"),
            },
            ["MotorcycleStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Akuma", "akuma", 7500, "Motorcycles"),
                new VehicleModel("Avarus", "avarus", 18000, "Motorcycles"),
                new VehicleModel("Bagger", "bagger", 15000, "Motorcycles"),
                new VehicleModel("Bati 801", "bati", 14000, "Motorcycles"),
                new VehicleModel("Bati 801RR", "bati2", 16000, "Motorcycles"),
                new VehicleModel("BF400", "bf400", 9000, "Motorcycles"),
                new VehicleModel("Carbon RS", "carbonrs", 18000, "Motorcycles"),
                new VehicleModel("Chimera", "chimera", 20000, "Motorcycles"),
                new VehicleModel("Cliffhanger", "cliffhanger", 12000, "Motorcycles"),
                new VehicleModel("Daemon", "daemon", 18000, "Motorcycles"),
                new VehicleModel("Defiler", "defiler", 10000, "Motorcycles"),
                new VehicleModel("Diablous Custom", "diablous2", 16000, "Motorcycles"),
                new VehicleModel("Diablous", "diablous", 16000, "Motorcycles"),
                new VehicleModel("Double T", "double", 15500, "Motorcycles"),
                new VehicleModel("Enduro", "enduro", 6000, "Motorcycles"),
                new VehicleModel("Esskey", "esskey", 9500, "Motorcycles"),
                new VehicleModel("Faggio 2", "faggio2", 2000, "Motorcycles"),
                new VehicleModel("Faggio 3", "faggio3", 2400, "Motorcycles"),
                new VehicleModel("Faggio", "faggio", 2500, "Motorcycles"),
                new VehicleModel("FCR Custom", "fcr2", 10000, "Motorcycles"),
                new VehicleModel("FCR", "fcr", 10000, "Motorcycles"),
                new VehicleModel("Gargoyle", "gargoyle", 16000, "Motorcycles"),
                new VehicleModel("Hakuchou Drag", "hakuchou2", 28000, "Motorcycles"),
                new VehicleModel("Hakuchou", "hakuchou", 22500, "Motorcycles"),
                new VehicleModel("Hexer", "hexer", 18000, "Motorcycles"),
                new VehicleModel("Innovation", "innovation", 20000, "Motorcycles"),
                new VehicleModel("Lectro", "lectro", 18000, "Motorcycles"),
                new VehicleModel("Manchez", "manchez", 8000, "Motorcycles"),
                new VehicleModel("Motocompo Scooter", "motoc", 2100, "Motorcycles"),
                new VehicleModel("Nemesis", "nemesis", 10000, "Motorcycles"),
                new VehicleModel("Nightblade", "nightblade", 18000, "Motorcycles"),
                new VehicleModel("PCJ 675", "pcj", 7000, "Motorcycles"),
                new VehicleModel("Ratbike", "ratbike", 7000, "Motorcycles"),
                new VehicleModel("Ruffian", "ruffian", 9000, "Motorcycles"),
                new VehicleModel("Sanchez", "sanchez", 7000, "Motorcycles"),
                new VehicleModel("Sanctus", "sanctus", 28000, "Motorcycles"),
                new VehicleModel("Sovereign", "sovereign", 16000, "Motorcycles"),
                new VehicleModel("Thrust", "thrust", 8000, "Motorcycles"),
                new VehicleModel("Vader", "vader", 9000, "Motorcycles"),
                new VehicleModel("Vindicator", "vindicator", 7000, "Motorcycles"),
                new VehicleModel("Vortex", "vortex", 21000, "Motorcycles"),
                new VehicleModel("Wolfsbane", "wolfsbane", 10000, "Motorcycles"),
                new VehicleModel("Zombie A", "zombiea", 12000, "Motorcycles"),
                new VehicleModel("Zombie B", "zombieb", 10000, "Motorcycles"),
            },
            ["UtilityStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Airtug", "airtug", 3000, "Small"),
                new VehicleModel("Caddy", "caddy", 5500, "Small"),
                new VehicleModel("Caddy 2", "caddy2", 2000, "Small"),
                new VehicleModel("Caddy 3", "caddy3", 3500, "Small"),
                new VehicleModel("Docktug", "docktug", 4000, "Small"),
                new VehicleModel("Forklift", "forklift", 9000, "Small"),
                new VehicleModel("Lawnmower", "mower", 4000, "Small"),
                new VehicleModel("Camper", "camper", 12000, "Vans"),
                new VehicleModel("Journey", "journey", 14000, "Vans"),
                new VehicleModel("Scrap Truck", "SCRAP", 15000, "Utility"),
                new VehicleModel("Tractor (Fieldmaster)", "tractor2", 9000, "Utility"),
                new VehicleModel("Tractor (Vintage)", "tractor", 3300, "Utility"),
                new VehicleModel("Tow Truck", "towtruck", 23000, "Utility"),
                new VehicleModel("Tow Truck 2", "towtruck2", 17800, "Utility"),
                new VehicleModel("Tour Bus", "tourbus", 17000, "Utility"),
                new VehicleModel("Utility Truck", "utillitruck", 24000, "Utility"),
                new VehicleModel("Utility Truck 2", "utillitruck2", 26000, "Utility"),
                new VehicleModel("Utility Pickup Truck", "utillitruck3", 30000, "Utility"),
                new VehicleModel("Benson", "benson", 22000, "Commercial"),
                new VehicleModel("Biff", "biff", 23000, "Commercial"),
                new VehicleModel("Hauler", "hauler", 25000, "Commercial"),
                new VehicleModel("Mule", "mule", 27000, "Commercial"), //mule 3?
                new VehicleModel("Packer", "packer", 35000, "Commercial"),
                new VehicleModel("Phantom", "phantom", 35000, "Commercial"),
                new VehicleModel("Pounder", "pounder", 34000, "Commercial"),
                new VehicleModel("Packer", "packer", 33000, "Commercial"),
                new VehicleModel("Dozer", "bulldozer", 70000, "Commercial"),
                new VehicleModel("Mixer", "mixer2", 32000, "Industrial"),
                new VehicleModel("Rubble", "rubble", 37000, "Industrial"),
                new VehicleModel("Tipper", "tiptruck", 33000, "Industrial"),
                new VehicleModel("Tipper 2", "tiptruck2", 36000, "Industrial"),
            },
            ["TunerStore"] = new List<VehicleModel>()
            {
                new VehicleModel("Mitsubishi Eclipse", "eclipse", 55000, "Tuners"),
                new VehicleModel("Mitsubishi Lancer Evo IX", "evo9", 75000, "Tuners"),
                new VehicleModel("Mitsubishi Lancer Evo VI", "cp9a", 65000, "Tuners"),
                new VehicleModel("Mitsubishi Lancer Evo X", "lancerevox", 90000, "Tuners"),
                new VehicleModel("Nissan 180sx", "180sx", 83500, "Tuners"),
                new VehicleModel("Nissan 370z", "370z", 110500, "Tuners"),
                new VehicleModel("Toyota Supra", "jza80", 80500, "Tuners"),
                new VehicleModel("Honda Integra", "dc2", 45000, "Tuners"),
                new VehicleModel("Honda S2000", "ap2", 72500, "Tuners"),
                new VehicleModel("Comet Retro", "comet3", 95000, "Tuners"),
                new VehicleModel("Elegy Retro", "elegy", 60000, "Tuners"),
            },
        };
    }
}
